# -*- coding: utf-8 -*-
"""Untitled14.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gU6RJ04y5GDlShmYo7N_O0UueOv8gMrx
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Import result
data=pd.read_csv('/content/Result.csv')


# Display the table
print("Model Ranking Table:")
print(data[['Model', 'Rouge_Scores', 'Length_of_Summary', 'Training_Time', 'Rank']].sort_values(by='Rank'))

# Bar chart
labels = data['Model']
num_models = len(labels)

# Parameters for bar chart
rouge_scores = data['Rouge_Scores']
length_of_summary = data['Length_of_Summary']
training_time = data['Training_Time']
ranks = data['Rank']

# Normalize ranks to a scale of 0 to 1 for better comparison
normalized_ranks = ranks / np.max(ranks)

# Plot the bar chart
fig, ax = plt.subplots(figsize=(10, 6))

bar_width = 0.5
index = range(num_models)

ax.bar(index, rouge_scores, width=bar_width, label='Rouge Scores')
ax.bar(index, length_of_summary, width=bar_width, label='Length of Summary', bottom=rouge_scores)
ax.bar(index, training_time, width=bar_width, label='Training Time', bottom=rouge_scores + length_of_summary)
ax.bar(index, normalized_ranks, width=bar_width, label='Normalized Rank', color='blue', alpha=0.5)

ax.set_xticks(index)
ax.set_xticklabels(labels)
ax.set_ylabel('Metrices')
ax.set_title('Text Summarization using Topsis')

ax.legend()
plt.show()